#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2025 KOOMOX
#
# <https://github.com/koomox/letsencrypt>
#

name: Update certificates

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  TimeZone: China Standard Time
  TARGET: /workdir

jobs:
  build_server:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Initialization environment
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p ${{ env.TARGET }}
          sudo chown $USER:$GROUPS ${{ env.TARGET }}
          GOPATH=$GITHUB_WORKSPACE

      - name: Deploy certificates.go
        run: |
          cd ${{ env.TARGET }}
          sudo cp -f $GITHUB_WORKSPACE/example/example.txt main.go
          go mod init letsencrypt
          go run main.go
          sudo rm -rf main.go
          sudo sha256sum ./certificates.go > ./certificates.sha256sum.txt

      - name: Prepare artifact
        run: |
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: certificates${{ env.FILE_DATE }}
          path: ${{ env.TARGET }}/certificates.go
